package lk.synergypharma.employee.data.api;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import lk.synergypharma.employee.data.mapper.AbsenceMapper;
import lk.synergypharma.employee.data.mapper.AttendanceMapper;
import lk.synergypharma.employee.data.mapper.EmployeeMapper;
import lk.synergypharma.employee.data.mapper.FeedMapper;
import lk.synergypharma.employee.data.mapper.LeaveMapper;
import lk.synergypharma.employee.data.remote.dto.AbsenceReasonDto;
import lk.synergypharma.employee.data.remote.dto.AnnouncementDto;
import lk.synergypharma.employee.data.remote.dto.AttendanceDayDto;
import lk.synergypharma.employee.data.remote.dto.ColleagueDto;
import lk.synergypharma.employee.data.remote.dto.EmployeeDto;
import lk.synergypharma.employee.data.remote.dto.HolidayDto;
import lk.synergypharma.employee.data.remote.dto.LeaveBalanceDto;
import lk.synergypharma.employee.data.remote.dto.LeaveRequestDto;
import lk.synergypharma.employee.data.remote.dto.MonthSummaryDto;
import lk.synergypharma.employee.data.remote.dto.NotificationDto;
import lk.synergypharma.employee.domain.model.AbsenceReason;
import lk.synergypharma.employee.domain.model.Announcement;
import lk.synergypharma.employee.domain.model.AppNotification;
import lk.synergypharma.employee.domain.model.Attachment;
import lk.synergypharma.employee.domain.model.AttendanceDay;
import lk.synergypharma.employee.domain.model.Colleague;
import lk.synergypharma.employee.domain.model.Employee;
import lk.synergypharma.employee.domain.model.LeaveRequest;
import lk.synergypharma.employee.domain.model.LeaveSnapshot;
import lk.synergypharma.employee.domain.model.MonthSummary;
import lk.synergypharma.employee.domain.model.Overtime;
import lk.synergypharma.employee.domain.model.RegistrationChallenge;
import lk.synergypharma.employee.domain.model.Session;
import lk.synergypharma.employee.domain.model.enums.LeaveType;
import lk.synergypharma.employee.util.DateTimeUtils;

/**
 * Runs the whole app without a backend.
 *
 * <p>Static parts (people, entitlements, holidays, the announcement feed) come
 * from {@code assets/mock}; everything date-shaped is generated by
 * {@link MockDataFactory} against today. Writes are kept in memory, so
 * submitting an absence reason really does clear the home-screen alert and
 * really does turn the calendar day from red — the demo behaves like the app,
 * not like a slideshow.
 *
 * <p>Every payload it produces is shaped like the live recognition database:
 * lowercase status values, {@code employee_code} identifiers, naive
 * space-separated timestamps and cosine-similarity confidences in the 0.5–0.7
 * band. That is deliberate — a mock that returns prettier data than reality
 * hides exactly the bugs it is supposed to surface.
 *
 * <p><b>Deleting this class is the last step of the project.</b>
 *
 * <h3>Demo logins</h3>
 * <ul>
 *   <li>{@code 1213} — Thisala Maduwinda, Junior Executive (employee)</li>
 *   <li>{@code 1001} — Ruwani Silva, QA Manager (supervisor)</li>
 * </ul>
 * Any password of four characters or more is accepted.
 */
public final class MockSynergyApi implements SynergyApi {

    /** Enough delay for the loading states to be visible and tested. */
    private static final long LATENCY_MS = 320L;

    private static final int MIN_PASSWORD = 4;

    /**
     * The code the mock "sends". Shown on screen only while
     * {@code BuildConfig.USE_MOCK_DATA} is true, so the hint cannot survive into
     * a build that talks to a real SMS gateway.
     */
    private static final String DEMO_OTP = "123456";

    private static final int OTP_TTL_SECONDS = 300;

    private static final LocalTime FALLBACK_SHIFT_START = LocalTime.of(8, 0);
    private static final LocalTime FALLBACK_SHIFT_END = LocalTime.of(17, 0);

    @NonNull
    private final Context context;
    @NonNull
    private final Gson gson = new Gson();
    @NonNull
    private final ExecutorService worker = Executors.newSingleThreadExecutor();
    @NonNull
    private final Handler main = new Handler(Looper.getMainLooper());

    // ---- in-memory state, so writes are visible for the rest of the session
    @Nullable
    private Employee currentEmployee;
    private final List<AbsenceReasonDto> submittedReasons = new ArrayList<>();
    private final List<LeaveRequestDto> extraLeaveRequests = new ArrayList<>();
    private final Set<String> correctionRequests = new HashSet<>();
    private final Set<String> registeredCodes = new HashSet<>();
    private boolean notificationsRead;
    private int idCounter = 1;

    // ---- outstanding registration challenge, one at a time
    @Nullable
    private MockRegistrationRecord pendingRegistration;
    @Nullable
    private String pendingChallengeToken;
    @Nullable
    private String pendingVerifiedToken;
    @Nullable
    private String pendingOtp;

    public MockSynergyApi(@NonNull Context context) {
        this.context = context.getApplicationContext();
    }

    // ------------------------------------------------------------------ auth

    @Override
    public void login(@NonNull String employeeId,
                      @NonNull String password,
                      @NonNull ApiCallback<Session> cb) {
        run(cb, () -> {
            if (password.length() < MIN_PASSWORD) {
                throw new MockException("Employee number or password is incorrect");
            }
            EmployeeDto dto = findEmployee(employeeId);
            if (dto == null) {
                throw new MockException("Employee number or password is incorrect");
            }
            currentEmployee = EmployeeMapper.toDomain(dto);
            return new Session("mock-access-token", "mock-refresh-token", currentEmployee);
        });
    }

    // ---------------------------------------------------------- registration

    @Override
    public void startRegistration(@NonNull String employeeCode,
                                  @NonNull String nic,
                                  @NonNull ApiCallback<RegistrationChallenge> cb) {
        run(cb, () -> {
            MockRegistrationRecord match = null;
            for (MockRegistrationRecord r : readRegistrationRecords()) {
                if (r.matches(employeeCode.trim(), nic)) {
                    match = r;
                    break;
                }
            }

            // One message for "no such code" and "wrong NIC" alike. Telling the
            // two apart would turn this screen into an employee-number scanner.
            if (match == null) {
                throw new MockException(
                        "That employee number and NIC do not match our records");
            }
            if (match.alreadyRegistered || registeredCodes.contains(match.employeeCode)) {
                throw new MockException(
                        "This employee number is already registered. Please sign in instead.");
            }

            pendingRegistration = match;
            pendingOtp = DEMO_OTP;
            String token = "chg-" + (idCounter++);
            pendingChallengeToken = token;
            pendingVerifiedToken = null;

            return new RegistrationChallenge(token, match.maskedPhone(),
                    OTP_TTL_SECONDS, DEMO_OTP.length(), DEMO_OTP);
        });
    }

    @Override
    public void verifyRegistrationOtp(@NonNull String challengeToken,
                                      @NonNull String otp,
                                      @NonNull ApiCallback<String> cb) {
        run(cb, () -> {
            if (pendingChallengeToken == null || !pendingChallengeToken.equals(challengeToken)) {
                throw new MockException("That request has expired. Please start again.");
            }
            if (pendingOtp == null || !pendingOtp.equals(otp.trim())) {
                throw new MockException("That code is not right. Check the SMS and try again.");
            }
            pendingVerifiedToken = "vrf-" + (idCounter++);
            return pendingVerifiedToken;
        });
    }

    @Override
    public void completeRegistration(@NonNull String verifiedToken,
                                     @NonNull String password,
                                     @NonNull ApiCallback<Session> cb) {
        run(cb, () -> {
            if (pendingVerifiedToken == null || !pendingVerifiedToken.equals(verifiedToken)
                    || pendingRegistration == null) {
                throw new MockException("That request has expired. Please start again.");
            }

            EmployeeDto dto = findEmployee(pendingRegistration.employeeCode);
            if (dto == null) {
                throw new MockException("Something went wrong. Please try again.");
            }

            registeredCodes.add(pendingRegistration.employeeCode);
            clearRegistrationState();

            // Registration ends signed in: making somebody who has just proved
            // who they are type it all again is pure friction.
            currentEmployee = EmployeeMapper.toDomain(dto);
            return new Session("mock-access-token", "mock-refresh-token", currentEmployee);
        });
    }

    private void clearRegistrationState() {
        pendingRegistration = null;
        pendingChallengeToken = null;
        pendingVerifiedToken = null;
        pendingOtp = null;
    }

    @NonNull
    private List<MockRegistrationRecord> readRegistrationRecords() {
        return readAsset("mock/registration.json",
                new TypeToken<List<MockRegistrationRecord>>() {
                }.getType());
    }

    @Override
    public void logout(@NonNull ApiCallback<Boolean> cb) {
        run(cb, () -> {
            currentEmployee = null;
            submittedReasons.clear();
            extraLeaveRequests.clear();
            correctionRequests.clear();
            clearRegistrationState();
            notificationsRead = false;
            return Boolean.TRUE;
        });
    }

    // ------------------------------------------------------------ attendance

    @Override
    public void attendanceMonth(@NonNull YearMonth month, @NonNull ApiCallback<MonthSummary> cb) {
        run(cb, () -> AttendanceMapper.toDomain(buildMonth(month)));
    }

    @Override
    public void attendanceDay(@NonNull LocalDate date, @NonNull ApiCallback<AttendanceDay> cb) {
        run(cb, () -> {
            MonthSummaryDto month = buildMonth(YearMonth.from(date));
            String iso = DateTimeUtils.toIso(date);
            for (AttendanceDayDto d : month.days) {
                if (iso.equals(d.workDate)) {
                    return AttendanceMapper.toDomain(d);
                }
            }
            throw new MockException("No record for " + DateTimeUtils.shortDate(date));
        });
    }

    @Override
    public void requestCorrection(@NonNull LocalDate date,
                                  @NonNull String message,
                                  @NonNull ApiCallback<Boolean> cb) {
        run(cb, () -> {
            correctionRequests.add(DateTimeUtils.toIso(date));
            return Boolean.TRUE;
        });
    }

    // ----------------------------------------------------------------- leave

    @Override
    public void leaveSnapshot(@NonNull ApiCallback<LeaveSnapshot> cb) {
        run(cb, () -> {
            Set<LocalDate> holidays = holidays();

            List<LeaveRequestDto> requests = new ArrayList<>(extraLeaveRequests);
            requests.addAll(MockDataFactory.leaveRequests(holidays));

            return new LeaveSnapshot(
                    LeaveMapper.toDomain(readLeaveBalances()),
                    holidays,
                    LeaveMapper.toRequests(requests));
        });
    }

    @Override
    public void applyLeave(@NonNull LeaveType type,
                           @NonNull LocalDate from,
                           @NonNull LocalDate to,
                           @NonNull LeaveRequest.DayPortion portion,
                           float days,
                           @NonNull String reason,
                           @Nullable String coveringOfficer,
                           @Nullable String approver,
                           @NonNull ApiCallback<LeaveRequest> cb) {
        run(cb, () -> {
            LeaveRequestDto dto = LeaveMapper.toDto(type, from, to, portion, days, reason,
                    coveringOfficer, approver);
            dto.id = "lv-new-" + (idCounter++);
            dto.status = "pending";
            extraLeaveRequests.add(0, dto);
            return LeaveMapper.toDomain(dto);
        });
    }

    // --------------------------------------------------------------- absence

    @Override
    public void absenceReasons(@NonNull ApiCallback<List<AbsenceReason>> cb) {
        run(cb, () -> AbsenceMapper.toReasons(new ArrayList<>(submittedReasons)));
    }

    @Override
    public void submitAbsenceReason(@NonNull AbsenceReason reason,
                                    @NonNull ApiCallback<AbsenceReason> cb) {
        run(cb, () -> {
            AbsenceReasonDto dto = AbsenceMapper.toDto(reason);
            dto.id = "abs-" + (idCounter++);
            dto.status = "pending";
            dto.submittedAt = MockDataFactory.isoNow();
            dto.attachments = new ArrayList<>();
            for (Attachment a : reason.attachments) {
                AbsenceReasonDto.AttachmentDto ad = new AbsenceReasonDto.AttachmentDto();
                ad.fileName = a.fileName;
                ad.sizeBytes = a.sizeBytes;
                ad.mimeType = a.mimeType;
                ad.url = a.localUri;
                dto.attachments.add(ad);
            }
            submittedReasons.add(dto);
            return AbsenceMapper.toDomain(dto);
        });
    }

    // -------------------------------------------------------------- overtime

    @Override
    public void overtime(@NonNull YearMonth month, @NonNull ApiCallback<Overtime> cb) {
        run(cb, () -> lk.synergypharma.employee.data.mapper.OvertimeMapper.toDomain(
                MockDataFactory.overtime(month, buildMonth(month))));
    }

    // ------------------------------------------------------- feed & contacts

    @Override
    public void announcements(@NonNull ApiCallback<List<Announcement>> cb) {
        run(cb, () -> {
            List<AnnouncementDto> dtos = readAsset("mock/announcements.json",
                    new TypeToken<List<AnnouncementDto>>() {
                    }.getType());
            for (AnnouncementDto d : dtos) {
                d.publishedAt = MockDataFactory.resolveRelativeTimestamp(d.publishedAt);
            }
            return FeedMapper.toAnnouncements(dtos);
        });
    }

    @Override
    public void notifications(@NonNull ApiCallback<List<AppNotification>> cb) {
        run(cb, () -> {
            YearMonth thisMonth = YearMonth.now();
            Set<LocalDate> holidays = holidays();
            LocalDate absent = MockDataFactory.absentDay(thisMonth, holidays);

            List<NotificationDto> dtos = MockDataFactory.notifications(
                    absent, buildMonth(thisMonth), isExplained(absent));

            if (notificationsRead) {
                for (NotificationDto d : dtos) {
                    d.read = true;
                }
            }
            return FeedMapper.toNotifications(dtos);
        });
    }

    @Override
    public void markAllNotificationsRead(@NonNull ApiCallback<Boolean> cb) {
        run(cb, () -> {
            notificationsRead = true;
            return Boolean.TRUE;
        });
    }

    @Override
    public void colleagues(@NonNull ApiCallback<List<Colleague>> cb) {
        run(cb, () -> {
            List<ColleagueDto> dtos = readAsset("mock/colleagues.json",
                    new TypeToken<List<ColleagueDto>>() {
                    }.getType());
            return EmployeeMapper.toColleagues(dtos);
        });
    }

    // ---------------------------------------------------------------- guts

    /**
     * Builds the month, then subtracts anything the employee has already
     * explained this session — that is what makes the red day on the calendar
     * change the moment a reason is submitted.
     */
    @NonNull
    private MonthSummaryDto buildMonth(@NonNull YearMonth month) {
        Employee employee = currentEmployee;

        Set<LocalDate> explained = new HashSet<>();
        for (AbsenceReasonDto r : submittedReasons) {
            LocalDate d = safeDate(r.workDate);
            if (d != null) {
                explained.add(d);
            }
        }

        return MockDataFactory.month(
                month,
                employee == null ? FALLBACK_SHIFT_START : employee.shiftStart,
                employee == null ? FALLBACK_SHIFT_END : employee.shiftEnd,
                holidays(),
                explained);
    }

    private boolean isExplained(@Nullable LocalDate date) {
        if (date == null) {
            return true;
        }
        String iso = DateTimeUtils.toIso(date);
        for (AbsenceReasonDto r : submittedReasons) {
            if (iso.equals(r.workDate)) {
                return true;
            }
        }
        return false;
    }

    /**
     * The calendar can be paged either side of this year, so the month-day
     * tokens are stamped onto three years rather than one.
     */
    @NonNull
    private Set<LocalDate> holidays() {
        List<HolidayDto> fixture = readAsset("mock/holidays.json",
                new TypeToken<List<HolidayDto>>() {
                }.getType());
        int year = LocalDate.now().getYear();

        Set<LocalDate> out = new HashSet<>();
        out.addAll(MockDataFactory.holidaysFor(year - 1, fixture));
        out.addAll(MockDataFactory.holidaysFor(year, fixture));
        out.addAll(MockDataFactory.holidaysFor(year + 1, fixture));
        return out;
    }

    @NonNull
    private List<LeaveBalanceDto> readLeaveBalances() {
        List<LeaveBalanceDto> rows = readAsset("mock/leave_balances.json",
                new TypeToken<List<LeaveBalanceDto>>() {
                }.getType());
        for (LeaveBalanceDto r : rows) {
            if (r.year <= 0) {
                r.year = LocalDate.now().getYear();
            }
        }
        return rows;
    }

    @Nullable
    private EmployeeDto findEmployee(@NonNull String enteredCode) {
        List<EmployeeDto> all = readAsset("mock/employees.json",
                new TypeToken<List<EmployeeDto>>() {
                }.getType());
        if (all.isEmpty()) {
            return null;
        }
        String needle = enteredCode.trim();
        for (EmployeeDto e : all) {
            if (needle.equalsIgnoreCase(e.employeeCode)) {
                return e;
            }
        }
        // Anything else logs in as the default employee so the app can be
        // demonstrated without handing out a list of valid codes first.
        return all.get(0);
    }

    @Nullable
    private static LocalDate safeDate(@Nullable String iso) {
        try {
            return iso == null ? null : DateTimeUtils.fromIso(iso);
        } catch (RuntimeException e) {
            return null;
        }
    }

    private <T> T readAsset(@NonNull String path, @NonNull Type type) {
        try (InputStream in = context.getAssets().open(path);
             BufferedReader reader = new BufferedReader(
                     new InputStreamReader(in, StandardCharsets.UTF_8))) {
            return gson.fromJson(reader, type);
        } catch (IOException e) {
            throw new MockException("Could not read " + path);
        }
    }

    /** Work the mock has to do, off the main thread. */
    private interface Job<T> {
        @NonNull
        T run() throws MockException;
    }

    /** Runs {@code job} on the worker thread and answers on the main thread. */
    private <T> void run(@NonNull ApiCallback<T> cb, @NonNull Job<T> job) {
        worker.execute(() -> {
            try {
                Thread.sleep(LATENCY_MS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
            try {
                T value = job.run();
                main.post(() -> cb.onSuccess(value));
            } catch (MockException e) {
                main.post(() -> cb.onError(e.getMessage() == null ? "Mock error" : e.getMessage()));
            } catch (RuntimeException e) {
                main.post(() -> cb.onError("Something went wrong. Please try again."));
            }
        });
    }

    /** Unchecked so the {@link Job} lambdas stay readable. */
    private static final class MockException extends RuntimeException {
        MockException(String message) {
            super(message);
        }
    }
}
